version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: tiger-timescaledb
    restart: always
    user: root # Temporarily runs container init as root to fix mounts
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/pgdata/data  # Uses subdirectory to avoid root permission error
      - POSTGRES_PASSWORD=password
    volumes:
      - tiger_data:/pgdata
      - ./init-tigerdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tiger-pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      timescaledb:
        condition: service_healthy

volumes:
  tiger_data: